flowchart LR
  m_jieshou_zhiding["接受指定与报备<br/>进行中 6 节点<br/>○1 ●1 ·4"]:::s1
  m_jieguan_diaocha["接管与调查<br/>进行中 7 节点<br/>·7"]:::s1
  m_jieshou_zhiding --> m_jieguan_diaocha
  m_zhaiquan_tongzhi["债权通知与审查<br/>进行中 7 节点<br/>·7"]:::s1
  m_jieguan_diaocha --> m_zhaiquan_tongzhi
  m_caichan_guanli["财产管理与追收<br/>进行中 8 节点<br/>·8"]:::s1
  m_zhaiquan_tongzhi --> m_caichan_guanli
  m_zhaiquanren_huiyi["债权人会议<br/>进行中 10 节点<br/>·10"]:::s1
  m_caichan_guanli --> m_zhaiquanren_huiyi
  m_queren_zhaiquan["申请确认债权<br/>进行中 2 节点<br/>·2"]:::s1
  m_zhaiquanren_huiyi --> m_queren_zhaiquan
  m_caichan_chuzhi["财产处置与确认成交<br/>进行中 6 节点<br/>·6"]:::s1
  m_queren_zhaiquan --> m_caichan_chuzhi
  m_xuangao_pochan["宣告破产<br/>进行中 3 节点<br/>·3"]:::s1
  m_caichan_chuzhi --> m_xuangao_pochan
  m_caichan_fenpei["财产分配<br/>进行中 6 节点<br/>·6"]:::s1
  m_xuangao_pochan --> m_caichan_fenpei
  m_zhongjie_zhuxiao["终结与注销<br/>进行中 9 节点<br/>·9"]:::s1
  m_caichan_fenpei --> m_zhongjie_zhuxiao
  m_zixing_hejie["自行和解<br/>进行中 2 节点<br/>·2"]:::s1
  m_zhongjie_zhuxiao --> m_zixing_hejie
  m_qiangzhi_qingsuan["强制清算<br/>进行中 6 节点<br/>·6"]:::s1
  m_zixing_hejie --> m_qiangzhi_qingsuan
  classDef s0 fill:#f4f4f5,stroke:#71717a,color:#18181b
  classDef s1 fill:#fde68a,stroke:#71717a,color:#18181b
  classDef s2 fill:#86efac,stroke:#71717a,color:#18181b
  classDef s3 fill:#e4e4e7,stroke:#71717a,color:#18181b
  classDef s4 fill:#ffffff,stroke:#71717a,color:#18181b